checks:
    php: true
build:
    nodes:
        tests: true
        analysis:
            environment:
                php: 7.0.20
filter:
    excluded_paths:
        - 'Test/*'
        - 'Modules/*'
        - 'Driver/CacheDriverFactory.php'
tools:
    external_code_coverage:
        timeout: 2400
    php_code_coverage:
        enabled: false
    php_cpd:
        excluded_dirs:
            - Test
    php_cs_fixer:
        config:
            level: psr2
        filter:
            excluded_paths:
                - 'Test/*'
                - 'Modules/*'
                - 'Driver/CacheDriverFactory.php'
    php_mess_detector:
        config:
            rulesets:
                - codesize
                - unusedcode
                - naming
                - design
            naming_rules:
                short_variable:
                    minimum: 2
        filter:
            excluded_paths:
                - 'Test/*'
                - 'Modules/*'
                - 'Driver/CacheDriverFactory.php'
