sudo: required

services:
  - docker

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: VERSION=7.1
    - php: 7.0
      env: VERSION=7.0

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install
  - mkdir -p build/logs
  - docker run --name test-memcached -p 21211:11211 -d memcached:1.5-alpine
  - docker run --name test-redis -p 16379:6379 -d redis:4.0-alpine

script:
  - if [[ $VERSION > 7.0 ]]; then docker run -v /home/travis/build/webstream-framework/Cache:/workspace/ --rm --link test-memcached:memcached --link test-redis:redis webstream/php-cli:$VERSION phpdbg -qrr vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.clover;
    else docker run -v /home/travis/build/webstream-framework/Cache:/workspace/ --rm --link test-memcached:memcached --link test-redis:redis webstream/php-cli:$VERSION vendor/bin/phpunit; fi

after_script:
  - docker rm -f test-memcached
  - docker rm -f test-redis
  - if [[ $VERSION = 7.1 ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $VERSION = 7.1 ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
