sudo: required

services:
  - docker

language: php

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - docker run -v /home/travis/build/webstream-framework/Container:/workspace/ webstream/php-alpine vendor/bin/phpunit --configuration phpunit.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

php:
  - 7.0
  - 7.1
